# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 10:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterData',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('the_geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('ingestion', models.DateTimeField(blank=True, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raster_data',
                'managed': True,
            },
        ),
    ]
